FROM python:{{ pythonversion }}-alpine

ENV WAITFORIT_VERSION="v1.4.0"

RUN set -x \
    && BASE_PKGS='su-exec bash curl' \
    && apk add --no-cache make ${BASE_PKGS} \
    && curl -o /usr/local/bin/waitforit -sSL https://github.com/maxcnunes/waitforit/releases/download/$WAITFORIT_VERSION/waitforit-linux_amd64 \
    && chmod +x /usr/local/bin/waitforit \
    && apk del --purge curl

COPY docker-entrypoint.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
