version: 2.0
jobs:
  build_python27:
    machine: true
    steps:
      - checkout

      # build and push Docker image
      - run: make build-python-2.7.14
  deploy_python27:
    docker:
      - image: ditchitall/python:2.7.14-alpine
      - image: ditchitall/python:2.7.14-jessie
    steps:
      - run: |
          docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
          make deploy-python-2.7.14
  build_python35:
    machine: true
    steps:
      - checkout

      # build and push Docker image
      - run: make build-python-3.5.4
  deploy_python35:
    docker:
      - image: ditchitall/python:3.5.4-alpine
      - image: ditchitall/python:3.5.4-jessie
    steps:
      - run: |
          docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
          make deploy-python-3.5.4
  build_python36:
    machine: true
    steps:
      - checkout

      # build and push Docker image
      - run: make build-python-3.6.4
  deploy_python36:
    docker:
      - image: ditchitall/python:3.6.4-alpine
      - image: ditchitall/python:3.6.4-jessie
    steps:
      - run: |
          docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
          make deploy-python-3.6.4

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_python27
      - build_python35
      - build_python36
      - deploy_python27:
          requires:
            - build_python27
          filters:
            branches:
              only: master
      - deploy_python35:
          requires:
            - build_python35
          filters:
            branches:
              only: master
      - deploy_python36:
          requires:
            - build_python36
          filters:
            branches:
              only: master
